Sofia.Office.Map.Web/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class EmployeeViewModel
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string Competence { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string UniqueAccountName { get; set; }
    }
}

Sofia.Office.Map.Web/Models/FloorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Busuness.Objects;

namespace Sofia.Office.Map.Web.Models
{
    public class FloorViewModel
    {
        public string Name { get; set; }
        public IEnumerable<Sector> Sectors { get; set; }
        public IEnumerable<Team> Teams { get; set; }
    }
}

Sofia.Office.Map.Web/Models/SectorEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Busuness.Objects;

namespace Sofia.Office.Map.Web.Models
{
    public class SectorEmployeeViewModel
    {
        public Sector Sector { get; set; }
        public Employee Employee { get; set; }
    }
}

Sofia.Office.Map.Web/Models/SectorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Busuness.Objects;

namespace Sofia.Office.Map.Web.Models
{
    public class SectorViewModel
    {
        public SectorViewModel(Floor floor)
        {
            this.Floor = floor;
            this.SectorId = 0;
        }
        public SectorViewModel(Floor floor, int sectorId = 0, Employee employee = null)
        {
            this.Floor = floor;
            this.Employee = employee;
            this.SectorId = sectorId;
        }
        public Floor Floor { get; set; }
        public int SectorId { get; set; }
        public Employee Employee { get; set; }
    }
}

Sofia.Office.Map.Web/Controllers/EmployeeController.cs
using System;
using System.Web.Mvc;
using Business.Services;
using Business.Services.Interfaces;
using Sofia.Office.Map.Web.Mapping;

namespace Sofia.Office.Map.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeLocationService employeeLocationService = BusinessManager.GetEmployeeLocationService();

        public ActionResult Index(string id)                                                        
        {
            var employees = employeeLocationService.GetEmployeesByNamePart(id);
            var emplyeeViewModels = Mapper.Map(employees);
            return Json(emplyeeViewModels, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(string id)                                                      
        {
            return PartialView(employeeLocationService.GetEmployee(id));

        }
        public ActionResult DetailsByPlaceId(string id)                                              
        {
            return PartialView("Details", employeeLocationService.GetEmployeeByWorkplace(Int32.Parse(id)));
        }
    }
}

Sofia.Office.Map.Web/Controllers/FloorController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Business.Services;
using Business.Services.Interfaces;
using Sofia.Office.Map.Web.Models;

namespace Sofia.Office.Map.Web.Controllers
{
    public class FloorController : Controller
    {
        private readonly IEmployeeLocationService employeeLocationService = BusinessManager.GetEmployeeLocationService();

        public ActionResult DeepDetails(int floorNumber, int? sectorNumber)                                
        {
            var floor = employeeLocationService.GetFloor(floorNumber);
            var sector = new SectorViewModel(floor);

            return View(sector);
        }

        public ActionResult Overview(int floorNumber)                                                         
        {
            var floor = employeeLocationService.GetFloor(floorNumber);
            var floorViewModel = Mapping.Mapper.Map(floor);
            return View(floorViewModel);
        }

        public ActionResult DeepDetailsWithSelectedEmployee(string id)                                  
        {
            var employee = employeeLocationService.GetEmployee(id);
            var floor = employeeLocationService.GetFloorBySector(employee.Sector);

            return View("DeepDetails", new SectorViewModel(floor, 0, employee));
        }                                                                                                  
    }
}

Sofia.Office.Map.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Services;
using Business.Services.Interfaces;

namespace Sofia.Office.Map.Web.Controllers
{
    public class HomeController : Controller
    {

        private readonly IEmployeeLocationService employeeLocationService = BusinessManager.GetEmployeeLocationService();

        public ActionResult Index()                                                         
        {
            var floors = employeeLocationService.GetFloorsWithInhabitantsAndTeams();
            return View(floors);
        }
    }
}

Sofia.Office.Map.Web/Controllers/SectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Services;
using Business.Services.Interfaces;
using Busuness.Objects;

namespace Sofia.Office.Map.Web.Controllers
{
    public class SectorController : Controller
    {
        private readonly IEmployeeLocationService employeeLocationService = BusinessManager.GetEmployeeLocationService();
        
        //public ActionResult Index(string id)
        //{
        //    return View(employeeLocationService.GetWorkplaces(Convert.ToInt32(id)));
        //}

        public JsonResult Workplaces(string id)
        {
            var sector = employeeLocationService.GetSector(Int32.Parse(id));
            return Json(sector, JsonRequestBehavior.AllowGet);
        }

    }
}

Sofia.Office.Map.Web/Views/Employee/Details.cshtml
@model Busuness.Objects.Employee

<div>
    <div>
        <div id="photo">
            <img src='@Html.DisplayFor(model => model.Photo)' alt="@Html.DisplayFor(model => model.Name)" style="border-radius: 50px; width: 64px; height: 64px;" />
        </div>
        <div id="details">
            <div id="who">
                <span id="person-name">@Html.DisplayFor(model => model.Name)</span>
                <span id="person-position">@Html.DisplayFor(model => model.Competence)</span>
            </div>
            <div id="where">
                <span id="location">@Html.DisplayFor(model => model.Sector)</span>
                <span id="solution-group"></span>
            </div>
        </div>
    </div>
</div>

Sofia.Office.Map.Web/Views/Employee/Index.cshtml
@model IEnumerable<Web.Models.EmployeeViewModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Competence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Competence)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            <img src='@Html.DisplayFor(modelItem => item.Photo)' alt="Image" style="border-radius: 50px;width: 64px;height: 64px;" />
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new {  id=item.UniqueAccountName }) |
        </td>
    </tr>
}

</table>

Sofia.Office.Map.Web/Views/Floor/DeepDetails.cshtml
@using Sofia.Office.Map.Web.Models
@model SectorViewModel

<div>
    <h4>@Model.Floor.Name Floor</h4>
    <hr />

    <ul class="nav nav-tabs sectors-nav-tabs">
        @foreach (var x in Model.Floor.Sectors)
        {
            <li id="@Html.Raw("sector")@x.Name@Html.Raw("tab")"><a data-toggle="tab" href="@Html.Raw("#sector")@x.Number">@x.Name</a></li>
        }
    </ul>

    <div class="tab-content">
        @foreach (var x in Model.Floor.Sectors)
        {
            <div id="@Html.Raw("sector")@x.Name" class="sectors tab-pane fade">
                @{
                    Html.RenderPartial("_sectorDetails", new SectorEmployeeViewModel { Sector = x, Employee = Model.Employee });
                }
            </div>
                    }
    </div>
</div>

<script>
    $(document)
        .ready(function() {
            @{
                var currentSector = Model.SectorId;
            }
            $(".sectors-nav-tabs li").removeClass("active");
            $(".sectors").removeClass("active in");
            if (@currentSector>0) {
                $('#sector' + @currentSector +'tab').addClass('active');
                $('#sector' + @currentSector).addClass('active in');
            } else {
                $('.sectors-nav-tabs li:first-child').addClass('active');
                $('.sectors:first-child').addClass('active in');
            }
        });
</script>

@section HeaderSearch{
    @{Html.RenderPartial("_employeeSearchForm");}
}
@section FloorDropdown{
    @{Html.RenderPartial("_floorDropdown");}
}

Sofia.Office.Map.Web/Views/Floor/Overview.cshtml
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.FloorViewModel

<svg width="200" height="400" id="sector215" class="sector">
    <polygon points="0 0, 0 300, 200 300, 200 130, 170 130, 170 50, 100 50, 100 0" style="fill:#11BAD7" />
    <text class="sector-name" x="20" y="200" font-family="Verdana" font-size="30" fill="white"></text>
    <text class="sector-teams" x="20" y="250" font-family="Verdana" font-size="15" fill="white"></text>
    Sorry, your browser does not support inline SVG.
</svg>
<svg width="500" height="400" id="sector205" class="sector">
    <polygon points="0 130, 0 300, 300 300, 300 130, 350 130, 350 250, 400 250, 400 350, 480 350, 500 50, 470 0, 150 0, 150 100, 100 100, 100 130" style="fill:#11BAD7" />
    <text class="sector-name" x="20" y="200" font-family="Verdana" font-size="30" fill="white"></text>
    <text class="sector-teams" x="20" y="250" font-family="Verdana" font-size="15" fill="white"></text>
    Sorry, your browser does not support inline SVG.
</svg> 

<script>
    var sectors = [];
    var sector_teams = [];
    @foreach (var s in Model.Sectors)
    {
        var floorIdentifier = s.FloorId;
        var sectorIdentifier = s.Number;
        var sectorId = "#sector"+sectorIdentifier;
        
            @:$('@sectorId' + ' .sector-name').html("Sector "+"@sectorIdentifier");
            var teams = new List<Team>
        {
            new Team
            {
                Name = "Team A"
            },
            new Team
            {
                Name = "Team B"
            }
        };
        foreach (var team in teams)
        {
                @:sector_teams.push("@team.Name");
                    @:$('@sectorId' + ' .sector-teams').append("@team.Name | ");
            }
        var url = Url.Action("DeepDetails", "Floor", new {floorNumber = @floorIdentifier, sectorNumber = @sectorIdentifier});
         @:$('@sectorId').wrap("<a href='@url'></a>");
    }

</script>
@section HeaderSearch{
    @{Html.RenderPartial("_employeeSearchForm");}
}
@section FloorDropdown{
    @{Html.RenderPartial("_floorDropdown");}
}

Sofia.Office.Map.Web/Views/Home/Index.cshtml
@model IEnumerable<Busuness.Objects.Floor>
@{
    ViewBag.Title = "Home Page";
}

<div class="row home">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h3>Search</h3>
        @{
            Html.RenderPartial("_employeeSearchForm");
        }
        <h3>Choose a floor</h3>

        @foreach (var floor in Model)
        {
            <div class="floor-block col-md-12">
                <a href="/Floor/Overview/?floorNumber=@floor.Number">
                    <div id="floor @floor.Name" class="floor-name col-md-2">
                        <span>@floor.Name</span>
                    </div>
                    <div id="floor @floor.Name+details" class="floor-details col-md-10">
                        <div class="floor-details-title">Who's there?</div>
                        <div class="floor-details-content">
                            <span>@floor.Inhabitans people</span> 
                            @foreach (var team in floor.Teams)
                            {
                               @Html.Raw(" | ") <span>@team.Name</span> 
                            }
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
    <div class="col-md-3"></div>
</div>

Sofia.Office.Map.Web/Views/Sector/Details.cshtml
@model Busuness.Objects.Sector

<div>
    <h4>Sector</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MapId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MapId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Floor.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Floor.Id)
        </dd>


    </dl>
</div>
<p>

    @Html.ActionLink("Back to List", "Index")
</p>

Sofia.Office.Map.Web/Views/Sector/Index.cshtml
@model IEnumerable<Busuness.Objects.Workplace>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee.Title)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Title)
            </td>

            <td>
                @Html.ActionLink("Employee details", "Details", "Employee", new { id = item.Employee.UniqueAccountName }, null) |
            </td>
        </tr>
    }

</table>

<a href="@Url.Action("Index", "Employee", new { id = UrlParameter.Optional })">Add an Admin</a>

Sofia.Office.Map.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/assets/styles/common.css")
    @Styles.Render("~/assets/styles/components.css")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("softserve | seating chart", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="col-md-6">
                @RenderSection("HeaderSearch", false)
                @RenderSection("FloorDropdown", false)
            </div>


        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            .
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Sofia.Office.Map.Web/Views/Shared/_employeeSearchForm.cshtml
<div class="col-md-9">
    @{
        using (MvcForm mvcForm = Html.BeginForm("DeepDetailsWithSelectedEmployee", "Floor", FormMethod.Post, new { @class = "navbar-form" }))
        {
            <div class="input-group col-sm-10">
                @Html.TextBox("ids", null, new { @class = "form-control typeahead", placeholder = "Search by name or position...", id = "srch-term", autocomplete = "off" })
                @Html.Hidden("id", null, new { @class = "form-control typeahead", id = "srch-term2", autocomplete = "off" })

                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        }
    }
</div>
<script src="@Url.Content("~/Scripts/autocomplete-search-box.js")" type="text/javascript"></script>

Sofia.Office.Map.Web/Views/Shared/_floorDropdown.cshtml
<script>
    $(function () {

        $(".dropdown-menu li a").click(function () {
            debugger
            $(".btn.dropdown-toggle:first-child").text($(this).text());
            $(".btn.dropdown-toggle:first-child").val($(this).text());
        });

    });
</script>

@*<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        Select floor
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="http://localhost:51310/Floor/DeepDetails/?floorNumber=2">2nd floor</a></li>
        <li><a href="http://localhost:51310/Floor/DeepDetails/?floorNumber=6">6th floor</a></li>
    </ul>
</div>*@


<div class="dropdown">
    <button class="dropbtn">Floors</button>
    <div class="dropdown-content">
        <a href="http://localhost:51310/Floor/DeepDetails/2">2nd floor</a>
        <a href="http://localhost:51310/Floor/DeepDetails/6">6th floor</a>
    </div>
</div>

Sofia.Office.Map.Web/Views/Shared/_sector1Map.cshtml
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    <h4>Sector</h4>
    <hr />
    <img src="" alt="54" />
</div>

Sofia.Office.Map.Web/Views/Shared/_sector205Map.cshtml
@using System.Web.UI.WebControls
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div class="svg-wrapper">
    <svg class="sector" data-trigger="focus">
    </svg>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var element;
        $('.workplace').click(function () {
            debugger 
            element = $(this);


            var empId = element.attr("id").substr(5);
            var url = '@Url.Action("DetailsByPlaceId", "Employee")' + '/' + empId;

            $.get(url, function (data) {
                $(element).popover({
                    html: true, content: data
                }).popover('show');
            });
        });
    });
</script>

Sofia.Office.Map.Web/Views/Shared/_sector206Map.cshtml
@using System.Web.UI.WebControls
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    <svg id="place26" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 60, 60 60, 60 0, 30 0, 30 30, 0 30" style="fill:green;" />
        Sorry, your browser does not support inline SVG.
    </svg>
    <svg id="place23" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 0, 0 60, 60 60, 60 30, 30 30, 30 0" style="fill:#00bfff;" />
        Sorry, your browser does not support inline SVG.
    </svg>
</div>

<script type="text/javascript">

    var WorkplacesArray = [];
    var current_employee;
    @*@foreach (var w in Model.Sector.Workplaces)
    {
        var placeNr = w.Id;
        var empUniqueName = w.Employee.UniqueAccountName;

        var placeId = "#place" + placeNr;

        @:WorkplacesArray["@placeNr"] = "@empUniqueName";
    }*@

        @*var workplaceId=0;
        var employeeId="";
        @if (Model.Employee != null)
        {
            @:workplaceId = @Model.Employee.Workplace.Id;
            @:employeeId = "@Model.Employee.UniqueAccountName";
        }*@


    $(document).ready(function () {

        @*if (employeeId!=="")
        {
            var url = '@Url.Action("Details", "Employee")' + '/' + employeeId;

            $.get(url, function (data) {
                $('#place' + workplaceId).popover({
                    html: true, content: data
                }).popover('show');
            });
        }*@
        var element;
        $('.workplace').click(function () {

            element = $(this);


            var empId = WorkplacesArray[element.attr("id").substr(5)];
            var url = '@Url.Action("Details", "Employee")' + '/' + empId;

            $.get(url, function (data) {
                $(element).popover({
                    html: true, content: data
                }).popover('show');
            });
        });

    });
</script>

Sofia.Office.Map.Web/Views/Shared/_sector2Map.cshtml
@using System.Web.UI.WebControls
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    <svg id="place26" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 60, 60 60, 60 0, 30 0, 30 30, 0 30" style="fill:#00bfff;" />
        Sorry, your browser does not support inline SVG.
    </svg>
    <svg id="place23" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 0, 0 60, 60 60, 60 30, 30 30, 30 0" style="fill:#00bfff;" />
        Sorry, your browser does not support inline SVG.
    </svg>
</div>

<script type="text/javascript">

    var WorkplacesArray = [];
    var current_employee;
    @foreach (var w in Model.Sector.Workplaces)
    {
        var placeNr = w.Id;
        var empUniqueName = w.Employee.UniqueAccountName;

        var placeId = "#place" + placeNr;

        @:WorkplacesArray["@placeNr"] = "@empUniqueName";
    }

        var workplaceId=0;
        var employeeId="";
        @if (Model.Employee != null)
        {
            @:workplaceId = @Model.Employee.Workplace.Id;
            @:employeeId = "@Model.Employee.UniqueAccountName";
        }
    
    
    $(document).ready(function () {

        if (employeeId!=="")
        {
            var url = '@Url.Action("Details", "Employee")' + '/' + employeeId;

            $.get(url, function (data) {
                $('#place' + workplaceId).popover({
                    html: true, content: data
                }).popover('show');
            });
        }
        var element;
        $('.workplace').click(function () {

            element = $(this);


            var empId = WorkplacesArray[element.attr("id").substr(5)];
            var url = '@Url.Action("Details", "Employee")' + '/' + empId;

            $.get(url, function (data) {
                $(element).popover({
                    html: true, content: data
                }).popover('show');
            });
            //$('*').not(element).popover('hide');
        });

        //$('body').not($('.workplace'))
        //    .click(function () {
        //        $('.workplace').not(element).popover('hide');
        //    });
    });
</script>

Sofia.Office.Map.Web/Views/Shared/_sector3Map.cshtml
@using System.Web.UI.WebControls
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    <svg id="place22" class="workplace" height="50" width="50" title="Nice tooltip22" data-trigger="focus">
        <polygon x="100" y="200" points="0 50,50 0,50 50" style="fill:pink;stroke:black;stroke-width:1" />
        Sorry, your browser does not support inline SVG.
    </svg>
    <svg id="place23" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 0,0 50,50 50" style="fill:pink;stroke:black;stroke-width:1" />
        Sorry, your browser does not support inline SVG.
    </svg>
</div>

<script type="text/javascript">

    var WorkplacesArray = [];

    @foreach (var w in Model)
    {
        var placeNr = w.Id;
        var empUniqueName = w.Employee.UniqueAccountName;

        var placeId = "#place" + placeNr;
        @*@:$("@placeId").wrap("<a href=\"#\"  data-poload=\"/Employee/Details/vbud\">Toggle popover</a>");*@

        @:WorkplacesArray["@placeNr"] = "@empUniqueName";
    }

    $(document).ready(function () {
        $('.workplace').click(function () {

            var element = $(this);
            var empId = WorkplacesArray[23];
            var url = '@Url.Action("Details", "Employee")'+'/'+empId;

            $.get(url, function (data) {
                console.log('aaa');

                $(element).popover({html: true, content: data
                }).popover('show');
            });



        });
        $('.workplace')
            .click(function () {
                debugger
                console.log('fff');
                $('.workplace').not(this).popover('hide');
            });
    });


    function GetContent() {
        @*@Html.Action("Details", "Employee", new { id = "vbud" });*@
    };


</script>

Sofia.Office.Map.Web/Views/Shared/_sector4Map.cshtml
@using System.Web.UI.WebControls
@using Busuness.Objects
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    <svg id="place22" class="workplace" height="50" width="50" title="Nice tooltip22" data-trigger="focus">
        <polygon x="100" y="200" points="50 50,50 0,0 50" style="fill:green;stroke:black;stroke-width:1" />
        Sorry, your browser does not support inline SVG.
    </svg>
    <svg id="place23" class="workplace" height="50" width="50" data-trigger="focus">
        <polygon x="100" y="200" points="0 50,50 50,0 0" style="fill:green;stroke:black;stroke-width:1" />
        Sorry, your browser does not support inline SVG.
    </svg>
</div>

<script type="text/javascript">

    var WorkplacesArray = [];

    @foreach (var w in Model)
    {
        var placeNr = w.Id;
        var empUniqueName = w.Employee.UniqueAccountName;

        var placeId = "#place" + placeNr;
        @*@:$("@placeId").wrap("<a href=\"#\"  data-poload=\"/Employee/Details/vbud\">Toggle popover</a>");*@

        @:WorkplacesArray["@placeNr"] = "@empUniqueName";
    }

    $(document).ready(function () {
        $('.workplace').click(function () {

            var element = $(this);
            var empId = WorkplacesArray[23];
            var url = '@Url.Action("Details", "Employee")'+'/'+empId;

            $.get(url, function (data) {
                console.log('aaa');

                $(element).popover({html: true, content: data
                }).popover('show');
            });



        });
        $('.workplace')
            .click(function () {
                debugger
                console.log('fff');
                $('.workplace').not(this).popover('hide');
            });
    });


    function GetContent() {
        @*@Html.Action("Details", "Employee", new { id = "vbud" });*@
    };


</script>

Sofia.Office.Map.Web/Views/Shared/_sectorDetails.cshtml
@model Sofia.Office.Map.Web.Models.SectorEmployeeViewModel

<div>
    @{
        var viewName = "_sector" + Model.Sector.Name + "Map";
        Html.RenderPartial(viewName, Model);
    }
</div>